#!/bin/sh

BITBUCKET_SERVER_XML="${BITBUCKET_INSTALL}/conf/server.xml"
BITBUCKET_CONNECTOR_SECURE_ATTR="secure"
BITBUCKET_CONNECTOR_SCHEME_ATTR="scheme"
BITBUCKET_CONNECTOR_PROXY_PORT_ATTR="proxyPort"
BITBUCKET_CONNECTOR_PROXY_NAME_ATTR="proxyName"

if [ ! -z "${BITBUCKET_CONNECTOR_PROXY_NAME}" ] && [ -z "$(xmlstarlet sel -t -c '//Connector[@proxyName]' ${BITBUCKET_SERVER_XML})" ]; then
    BITBUCKET_CONNECTOR_SECURE=${BITBUCKET_CONNECTOR_SECURE:-true}
    BITBUCKET_CONNECTOR_SCHEME=${BITBUCKET_CONNECTOR_SCHEME:-https}
    BITBUCKET_CONNECTOR_PROXY_PORT=${BITBUCKET_CONNECTOR_PROXY_PORT:-443}

    echo "+${BITBUCKET_SERVER_XML}://Connector[@port=7990] ${BITBUCKET_CONNECTOR_SECURE_ATTR}=\"${BITBUCKET_CONNECTOR_SECURE}\""
    echo "+${BITBUCKET_SERVER_XML}://Connector[@port=7990] ${BITBUCKET_CONNECTOR_SCHEME_ATTR}=\"${BITBUCKET_CONNECTOR_SCHEME}\""
    echo "+${BITBUCKET_SERVER_XML}://Connector[@port=7990] ${BITBUCKET_CONNECTOR_PROXY_PORT_ATTR}=\"${BITBUCKET_CONNECTOR_PROXY_PORT}\""
    echo "+${BITBUCKET_SERVER_XML}://Connector[@port=7990] ${BITBUCKET_CONNECTOR_PROXY_NAME_ATTR}=\"${BITBUCKET_CONNECTOR_PROXY_NAME}\""

    xmlstarlet ed --inplace \
            --insert '//Connector[@port=7990]' -t attr -n ${BITBUCKET_CONNECTOR_SECURE_ATTR} -v ${BITBUCKET_CONNECTOR_SECURE} \
            --insert '//Connector[@port=7990]' -t attr -n ${BITBUCKET_CONNECTOR_SCHEME_ATTR} -v ${BITBUCKET_CONNECTOR_SCHEME} \
            --insert '//Connector[@port=7990]' -t attr -n ${BITBUCKET_CONNECTOR_PROXY_PORT_ATTR} -v ${BITBUCKET_CONNECTOR_PROXY_PORT} \
            --insert '//Connector[@port=7990]' -t attr -n ${BITBUCKET_CONNECTOR_PROXY_NAME_ATTR} -v ${BITBUCKET_CONNECTOR_PROXY_NAME} \
        ${BITBUCKET_SERVER_XML}
fi

echo "=${BITBUCKET_SERVER_XML}:"
xmlstarlet sel -t -c '//Connector[@port=7990]' ${BITBUCKET_SERVER_XML} | fold -s | sed -e '2,$s/^/    /g' -e 's/^/    /g'
echo
